<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'ClienteSolictud Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'index.html',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'prueba@hotmail.com',
		'to' => 'prueba@hotmail.com'
	),
	'fields' => array(
		'custom_U14687' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Nombre',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Nombre\' is required.'
			)
		),
		'custom_U14714' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Monto Solicitado',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Monto Solicitado\' is required.'
			)
		),
		'custom_U14708' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Tel. No',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Tel. No\' is required.'
			)
		),
		'custom_U14726' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Apellidos',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Apellidos\' is required.'
			)
		),
		'custom_U14944' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Destino del Prestamo',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Destino del Prestamo\' is required.'
			)
		),
		'custom_U14987' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.'
			)
		),
		'custom_U14999' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Cedula',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Cedula\' is required.'
			)
		),
		'custom_U15011' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Fecha de Nacimiento',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Fecha de Nacimiento\' is required.'
			)
		),
		'custom_U15023' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Empresa',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Empresa\' is required.'
			)
		),
		'custom_U15035' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'Puesto',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Puesto\' is required.'
			)
		),
		'custom_U15047' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Telefono',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Telefono\' is required.'
			)
		),
		'custom_U15071' => array(
			'order' => 13,
			'type' => 'string',
			'label' => 'Ingresos',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Ingresos\' is required.'
			)
		),
		'custom_U15091' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Direccion',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Direccion\' is required.'
			)
		),
		'custom_U15118' => array(
			'order' => 15,
			'type' => 'string',
			'label' => ' Nombre',
			'required' => true,
			'errors' => array(
				'required' => 'Field \' Nombre\' is required.'
			)
		),
		'custom_U15130' => array(
			'order' => 18,
			'type' => 'string',
			'label' => 'Tel. No',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Tel. No\' is required.'
			)
		),
		'custom_U15142' => array(
			'order' => 22,
			'type' => 'string',
			'label' => 'Fecha de Nacimiento',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Fecha de Nacimiento\' is required.'
			)
		),
		'custom_U15154' => array(
			'order' => 17,
			'type' => 'string',
			'label' => 'Cedula',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Cedula\' is required.'
			)
		),
		'custom_U15335' => array(
			'order' => 14,
			'type' => 'string',
			'label' => 'Descripcion Garantia (Si es Hipotecario)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Descripcion Garantia (Si es Hipotecario)\' is required.'
			)
		),
		'custom_U15347' => array(
			'order' => 21,
			'type' => 'string',
			'label' => 'Direccion',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Direccion\' is required.'
			)
		),
		'custom_U15359' => array(
			'order' => 24,
			'type' => 'string',
			'label' => 'Trabajo',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Trabajo\' is required.'
			)
		),
		'custom_U15371' => array(
			'order' => 25,
			'type' => 'string',
			'label' => 'Telefono',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Telefono\' is required.'
			)
		),
		'custom_U15383' => array(
			'order' => 26,
			'type' => 'string',
			'label' => 'Puesto',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Puesto\' is required.'
			)
		),
		'custom_U15395' => array(
			'order' => 27,
			'type' => 'string',
			'label' => 'Ingreso',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Ingreso\' is required.'
			)
		),
		'custom_U17054' => array(
			'order' => 16,
			'type' => 'string',
			'label' => 'Apellidos',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Apellidos\' is required.'
			)
		),
		'custom_U17066' => array(
			'order' => 20,
			'type' => 'string',
			'label' => 'Celular No',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Celular No\' is required.'
			)
		),
		'custom_U17301' => array(
			'order' => 23,
			'type' => 'string',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.'
			)
		),
		'custom_U17240' => array(
			'order' => 19,
			'type' => 'radiogroup',
			'label' => 'Sexo',
			'required' => true,
			'optionItems' => array(
				'M',
				'F'
			),
			'errors' => array(
				'required' => 'Field \'Sexo\' is required.',
				'format' => 'Field \'Sexo\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
