<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'ClienteConfiguracion Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'index.html',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'prueba@hotmail.com',
		'to' => 'prueba@hotmail.com'
	),
	'fields' => array(
		'custom_U16892' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'User Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'User Name\' is required.'
			)
		),
		'custom_U16882' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'custom_U16887' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Last Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Last Name\' is required.'
			)
		),
		'custom_U16873' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Cedula',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Cedula\' is required.'
			)
		),
		'custom_U16914' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Telefono',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Telefono\' is required.'
			)
		),
		'custom_U16909' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Celular',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Celular\' is required.'
			)
		),
		'custom_U16869' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Fecha de Nacimiento',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Fecha de Nacimiento\' is required.'
			)
		),
		'custom_U16918' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Direccion',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Direccion\' is required.'
			)
		),
		'custom_U16878' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.'
			)
		),
		'custom_U16896' => array(
			'order' => 10,
			'type' => 'radiogroup',
			'label' => 'Sex',
			'required' => true,
			'optionItems' => array(
				'M',
				'F'
			),
			'errors' => array(
				'required' => 'Field \'Sex\' is required.',
				'format' => 'Field \'Sex\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
